"""add percentage column to exchange_rates

Revision ID: 3810e3cf4647
Revises: 2fdc33e0ffe8
Create Date: 2025-07-02 02:17:11.660053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3810e3cf4647'
down_revision: Union[str, None] = '2fdc33e0ffe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'percentage')
    # ### end Alembic commands ###
