"""add manual rate

Revision ID: 6c944cbbd5a0
Revises: b5c6d7e8f9a0
Create Date: 2025-07-27 21:23:48.589709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c944cbbd5a0'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('manual_rate', sa.Float(), nullable=True))
    op.add_column('exchange_rates', sa.Column('is_manual', sa.Boolean(), nullable=True))
    op.add_column('exchange_rates', sa.Column('automatic_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'automatic_rate')
    op.drop_column('exchange_rates', 'is_manual')
    op.drop_column('exchange_rates', 'manual_rate')
    # ### end Alembic commands ###
