"""Add inverse_percentage column to exchange_rates

Revision ID: 8b98fc2d3def
Revises: ffa3898850d6
Create Date: 2025-06-16 12:38:26.399488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b98fc2d3def'
down_revision: Union[str, None] = 'ffa3898850d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('inverse_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'inverse_percentage')
    # ### end Alembic commands ###
