"""add_binance_tracked_field_to_currency_pairs

Revision ID: a3b4c5d6e7f8
Revises: 462ef9732da7
Create Date: 2025-07-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b4c5d6e7f8'
down_revision: Union[str, None] = '462ef9732da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add binance_tracked field to currency_pairs table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_pairs', sa.Column('binance_tracked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove binance_tracked field from currency_pairs table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_pairs', 'binance_tracked')
    # ### end Alembic commands ###