"""add_binance_tracking_fields_to_currency_pairs

Revision ID: b5c6d7e8f9a0
Revises: a3b4c5d6e7f8
Create Date: 2025-07-15 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c6d7e8f9a0'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add banks_to_track and amount_to_track fields to currency_pairs table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_pairs', sa.Column('banks_to_track', sa.JSON(), nullable=True))
    op.add_column('currency_pairs', sa.Column('amount_to_track', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove banks_to_track and amount_to_track fields from currency_pairs table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_pairs', 'amount_to_track')
    op.drop_column('currency_pairs', 'banks_to_track')
    # ### end Alembic commands ###