"""add_currency_pairs_table

Revision ID: bcc069818759
Revises: dfa81171770a
Create Date: 2025-07-02 15:27:50.928155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc069818759'
down_revision: Union[str, None] = 'dfa81171770a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency_id', sa.Integer(), nullable=False),
    sa.Column('to_currency_id', sa.Integer(), nullable=False),
    sa.Column('pair_symbol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['to_currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_id', 'to_currency_id', name='unique_currency_pair')
    )
    op.create_index(op.f('ix_currency_pairs_id'), 'currency_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_currency_pairs_pair_symbol'), 'currency_pairs', ['pair_symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_pairs_pair_symbol'), table_name='currency_pairs')
    op.drop_index(op.f('ix_currency_pairs_id'), table_name='currency_pairs')
    op.drop_table('currency_pairs')
    # ### end Alembic commands ###
