"""Add derived rate configuration to CurrencyPair

Revision ID: f37dc49de924
Revises: ff8c00f2424d
Create Date: 2025-08-13 19:49:19.991455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37dc49de924'
down_revision: Union[str, None] = 'ff8c00f2424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_pairs', sa.Column('derived_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('currency_pairs', sa.Column('use_inverse_percentage', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_pairs', 'use_inverse_percentage')
    op.drop_column('currency_pairs', 'derived_percentage')
    # ### end Alembic commands ###
