"""change-inverse-percentage-type-in-rates-table

Revision ID: f3d335c9191c
Revises: 3810e3cf4647
Create Date: 2025-07-02 02:28:24.373538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d335c9191c'
down_revision: Union[str, None] = '3810e3cf4647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'inverse_percentage')
    op.add_column('exchange_rates', sa.Column('inverse_percentage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_rates', 'inverse_percentage',
               existing_type=sa.Boolean(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
