"""Add base_pair_id to CurrencyPair table

Revision ID: ff8c00f2424d
Revises: 6c944cbbd5a0
Create Date: 2025-08-13 19:04:47.170532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8c00f2424d'
down_revision: Union[str, None] = '6c944cbbd5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_pairs', sa.Column('base_pair_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currency_pairs', 'currency_pairs', ['base_pair_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_pairs', type_='foreignkey')
    op.drop_column('currency_pairs', 'base_pair_id')
    # ### end Alembic commands ###
